Basic widgets in progress
thoughtspot/plugin-party pull request #16
Opened 2023-03-07 14:21 UTC by Nirmay15

2023-03-09 09:48 UTC, ashubham requested changes

2023-03-09 09:48 UTC, ashubham commented on packages/slides/src/ui/components/home/home.tsx
> +  if (browse) return <ListPage setTest={setTest} />;
Will be great to add a router instead of using local state. I will do that. Can leave it like this for now.

2023-03-09 09:48 UTC, ashubham commented on packages/i18n/strings/en.json
> +  "INSERT_TEXT": "Insert Thoughtspot Visualizations",
Lets have a more descriptive key. A good rule of thumb is to take the first 2-3 words of the value. The key should not have semantic usage details like "subtext" as they may be used as something else tmrw. So they better represent the string being translated.

2023-03-09 09:48 UTC, ashubham commented on packages/slides/src/ui/services/api.ts
> +  const answerList = data.filter((object) => object.metadata_type === 'ANSWER');
one approach here would be to use _.keyBy that prevents 2 iterations on the list.

2023-03-09 09:48 UTC, ashubham commented on packages/widgets/custom-typings/html.d.ts
> +declare module '*.html' {
why do we need these custom typings ?

2023-03-09 09:48 UTC, ashubham commented on packages/widgets/custom-typings/scss-modules.d.ts
> +declare module '*.scss' {
We havent been using scss modules otherwise in other widgets. Might be good to be consistent.

2023-03-09 09:48 UTC, ashubham commented on packages/widgets/src/avatar/avatar.tsx
> +  console.log(randomBgClassName);
remove

2023-03-09 09:48 UTC, ashubham commented on packages/widgets/src/avatar/avatar.tsx
> +  // console.log(imageSrc);
were we able to find a solution here ?

2023-03-09 09:48 UTC, ashubham commented on packages/widgets/src/avatar/avatar.tsx
> +    console.log(showName, name, nameWithPrefix);
remove

2023-03-09 09:48 UTC, ashubham commented on packages/widgets/src/avatar/avatar.tsx
> +              {name[0]}
Do we need to capitalize ?

2023-03-09 09:48 UTC, ashubham commented on packages/widgets/src/card/card-body.tsx
> +import React from 'react';
preact

2023-03-09 09:48 UTC, ashubham commented on packages/widgets/src/card/card.tsx
> +      <CardBody>
CardBody seems like a thin wrapper which just adds a div with classNames, do we need to create the extra component layer ?

2023-03-09 09:48 UTC, ashubham commented on packages/widgets/src/card/card.tsx
> +  firstButtonClick?: () => void;
onFirstButtonClick

2023-03-09 09:48 UTC, ashubham commented on packages/widgets/src/card/card.tsx
> +  secondButtonClick?: () => void;
onSecondButtonClick

2023-03-09 09:48 UTC, ashubham commented on packages/widgets/src/card/card.tsx
> +  firstButtonDisable?: boolean;
isFistButtonDisabled

2023-03-09 09:48 UTC, ashubham commented on packages/widgets/src/card/card.tsx
> +  secondButtonDisable?: boolean;
isSecondButtonDisabled

2023-03-09 09:48 UTC, ashubham commented on packages/widgets/src/card/card.tsx
> +  firstButtonHide?: boolean;
isFirstButtonHidden

2023-03-09 09:48 UTC, ashubham commented on packages/widgets/src/card/card.tsx
> +  secondButtonHide?: boolean;
isSecondButtonHidden

2023-03-09 09:48 UTC, ashubham commented on packages/widgets/src/avatar/avatar.tsx
> +}
Do we need all these above props for our use cases ? Lets not bring complexity preemptively. It increases application size and hence load time.

2023-03-09 09:48 UTC, ashubham commented on packages/widgets/src/avatar/avatar.module.scss
> +}
Large CSS = Large load time. Lets be judicious of what we write.

2023-03-09 09:48 UTC, ashubham commented on packages/widgets/src/colors.scss
> +//   ========================================================================
Now that we have multiple of these, would be great to move them into a "common" directory.

2023-03-09 09:48 UTC, ashubham commented on packages/widgets/src/icon/icon.tsx
> +import cx from 'classnames';
you can skip the icons for now. I am in the progress of implementing and we dont want merge conflicts.

2023-03-09 09:48 UTC, ashubham commented on packages/widgets/src/mixins.scss
> +$rd-font--size-p:   14px !default;
these are not mixins, create a text.scss ?

2023-03-09 09:48 UTC, ashubham commented on packages/widgets/src/mixins.scss
> +}
We do not need to support older browsers anymore. I feel these flex mixins are useless and just bloat the CSS size.

2023-03-09 09:48 UTC, ashubham commented on packages/widgets/src/mixins.scss
> +    .ie & {
f**k IE.

2023-03-09 09:48 UTC, ashubham commented on packages/widgets/src/mixins.scss
> +@include flex-basis($basis);
I feel its better to use these properties directly. The mixins do not provide any real value anymore as most browsers have now aligned their flex interface.

2023-03-09 09:48 UTC, ashubham commented on packages/widgets/src/tab/tab-item.tsx
> +}
we do not seem to be using any of this, lets restrict the interface to what we really need.

2023-03-10 13:45 UTC, Nirmay15 commented on packages/widgets/custom-typings/scss-modules.d.ts
> +declare module '*.scss' {
Used scss modules for other widgets also

2023-03-10 13:46 UTC, Nirmay15 commented on packages/widgets/src/avatar/avatar.module.scss
> +}
removed unnecessary classes others are required.

2023-03-10 13:50 UTC, Nirmay15 commented on packages/i18n/strings/en.json
> +  "INSERT_TEXT": "Insert Thoughtspot Visualizations",
Updated Keys let me know if they looks good

2023-03-10 13:55 UTC, Nirmay15 commented on packages/slides/src/ui/services/api.ts
> +  const answerList = data.filter((object) => object.metadata_type === 'ANSWER');
used _.groupBy to group data, _.keyBy was returning just last object with provided key.

2023-03-10 13:56 UTC, Nirmay15 commented on packages/widgets/src/avatar/avatar.tsx
> +  // console.log(imageSrc);
added base url to the call it is working now earlier I was trying to call profile pic through localhost:5174

2023-03-10 13:56 UTC, Nirmay15 commented on packages/widgets/src/card/card.tsx
> +      <CardBody>
Removed card body as a component added required class in div it self

2023-03-10 13:57 UTC, Nirmay15 commented on packages/widgets/src/icon/icon.tsx
> +import cx from 'classnames';
removed icon folder

2023-03-14 04:27 UTC, merged