SCAL-149896 : fix list height
thoughtspot/plugin-party pull request #23
Opened 2023-03-30 10:39 UTC by Nirmay15

2023-03-30 18:52 UTC, ashubham requested changes
I have the required changes as part of a PR.

2023-03-30 18:52 UTC, ashubham commented on packages/widgets/src/list/list-item.module.scss
> +    height: 75vh;
how did we come up with 75vh ? It will break on taller screens

2023-03-30 18:52 UTC, ashubham commented on packages/widgets/src/list/list.tsx
> +  if (listViewPortHeight > listScrollHeight && !isLoading && !isLastBatch) {
lets not use javascript to style.

2023-03-30 20:04 UTC, Nirmay15 commented on packages/widgets/src/list/list-item.module.scss
> +    height: 75vh;
For 100% window zoom of mac screen ( for this plugin is of height 873px ) we had list height 650px, which makes it approx 74.5vh thats why I am using 75vh, isn't using vh when changing height of an element with screen a good idea?

2023-03-31 04:55 UTC, ashubham requested changes

2023-03-31 04:55 UTC, ashubham commented on packages/widgets/src/list/list-item.module.scss
> +    height: 75vh;
What if you use on a 4k monitor where height is 2160 pixels ? Then the height of the list is .75*2160 =1620 and the bottom icons are 500pixels ?

2023-03-31 04:55 UTC, ashubham commented on packages/widgets/src/list/list.tsx
> +  if (listViewPortHeight > listScrollHeight && !isLoading && !isLastBatch) {
got it, lets use `refs` to access DOM in react.

2023-04-03 19:37 UTC, ashubham approved these changes

2023-04-03 19:37 UTC, merged