LB viz insert support
thoughtspot/plugin-party pull request #28
Opened 2023-04-19 13:42 UTC by Nirmay15

2023-04-20 03:55 UTC, ashubham requested changes

2023-04-20 03:55 UTC, ashubham commented on packages/slides/src/server/Code.ts
> +  const clusterUrl = getClusterUrl().url.split('/')[0];
This would fail if the user had https:// in their input ? Maybe we use some standard url parsing

2023-04-20 03:55 UTC, ashubham commented on packages/slides/src/server/Code.ts
> +    const currentCluster = getClusterUrl().url.split('/')[0];
We should avoid repetition to maintain consistr

2023-04-20 03:55 UTC, ashubham commented on packages/slides/src/ui/components/liveboard/liveboard.tsx
> +    lbRef.current.on('insertInToSlide', (e) => {
Use enum

2023-04-20 15:13 UTC, Nirmay15 commented on packages/slides/src/server/Code.ts
> +  const clusterUrl = getClusterUrl().url.split('/')[0];
in setClusterUrl we are removing, https://, # and trailing '/' now, we will just have domain string

2023-04-20 15:16 UTC, Nirmay15 commented on packages/slides/src/server/Code.ts
> +    const currentCluster = getClusterUrl().url.split('/')[0];
split('/')[0]; thing will be not used now removing all the tailing '/' from the URL in setClusterUrl function. Moved currentCluster out of filter will be called once.

2023-04-25 03:08 UTC, ashubham approved these changes

2023-04-25 03:36 UTC, merged