Vercel plugin Changes for new flow
thoughtspot/plugin-party pull request #53
Opened 2023-11-06 13:35 UTC by adityamittal3107

2023-11-17 13:37 UTC, abdullasulaiman requested changes
Initial review. Please take a look at this. I will continue with other changes as well

2023-11-17 13:37 UTC, abdullasulaiman commented on packages/vercel/src/app.context.tsx
> +  projectEnv?: any;
Can we type it full projectEnvironment ?

2023-11-17 13:37 UTC, abdullasulaiman commented on packages/vercel/src/app.context.tsx
> +  vercelToken?: string;
why do we need to name it as vercelToken is there any other token we are defining to keep the differentiation

2023-11-17 13:37 UTC, abdullasulaiman commented on packages/vercel/src/app.context.tsx
> +const reducer: any = (state, action) => {
Can we define the type of reduce as below
type Action =
  | { type: AppConfigActions.SELECTED_PROJECT; newSelectedProject: string }
  | { type: AppConfigActions.VERCEL_TOKEN; newVercelToken: string }
.....

type State = AppConfigInterface;

const reducer = (state: State, action: Action): State => {
  // ... your existing reducer logic
};

2023-11-17 13:37 UTC, abdullasulaiman commented on packages/vercel/src/app.context.tsx
> +        selecteDataSources: action.newSelectDataSources,
typo change from **selecteDataSources** to **selectDataSources**

2023-11-17 14:39 UTC, abdullasulaiman requested changes
Initial review. Please take a look at this. I will continue with other changes as well

2023-11-17 14:39 UTC, abdullasulaiman commented on packages/vercel/src/app.tsx
> +//import { getCurrentUserInfo, getVercelAccessToken } from './service/vercel-api';
Please remove this line

2023-11-17 14:39 UTC, abdullasulaiman commented on packages/vercel/src/app.module.scss
> +    min-width: 195px !important;
Can we define this with percentage and why !important is required ?

2023-11-17 14:39 UTC, abdullasulaiman commented on packages/vercel/src/app.module.scss
> +    padding: 20px;
is padding can be replaced with margin. avoid random numbers like 20px ?

2023-11-17 14:39 UTC, abdullasulaiman commented on packages/vercel/src/app.tsx
>    const [clusterUrl, setClusterUrl] = useState<any>({
Can we define the type here as { url, isCandidate } instead of any

2023-11-17 14:39 UTC, abdullasulaiman commented on packages/vercel/src/app.tsx
> +  if (deploymentUrl) {
Should we not handle else case here if the url is not defined. Are we considering that ?

2023-11-17 14:39 UTC, abdullasulaiman commented on packages/vercel/src/app.tsx
> +  // useEffect(() => {
Remove this

2023-11-17 14:39 UTC, abdullasulaiman commented on packages/vercel/src/app.tsx
> +  const history: any = createMemoryHistory();
Can we type any with History Type ?

2023-11-17 14:39 UTC, abdullasulaiman commented on packages/vercel/src/app.tsx
> +  const deploymentUrlSearchParam = new URLSearchParams(searchParams[2]);
This can be a potential undefined ( runtime error ) with searchParams[2]

2023-11-17 14:39 UTC, abdullasulaiman commented on packages/vercel/src/app.tsx
> +  const searchParams = url.split('?');
Can we define the type what we are looking in searchParams. Not readable

2023-11-17 14:39 UTC, abdullasulaiman commented on packages/vercel/src/app.tsx
>  import React from 'preact';
Consider providing more explicit type definitions for your variables. This can enhance readability and catch potential errors early.
example : 
const addedSearchParam = new URLSearchParams(searchParams[1]);
const clusterId = addedSearchParam.get('clusterUrl');
Scan through the code and do necessary changes

2023-11-17 14:39 UTC, abdullasulaiman commented on packages/vercel/src/components/connection/connection-utils.tsx
> +export default function findConnectedComponents(
Can we comment what's the purpose of this function. It is trying to do a lot of things and the usage in the comment block that will help.

2023-11-17 14:39 UTC, abdullasulaiman commented on packages/vercel/src/components/connection/connection-utils.tsx
> +export const steps = [
Can we type as steps: Step[] ?
type Step {
 title: string,
 isSubStep?: boolean
}

2023-11-17 14:39 UTC, abdullasulaiman commented on packages/vercel/src/components/connection/connection-utils.tsx
> +export default function findConnectedComponents(
Consider adding error handling for unexpected or invalid inputs to findConnectedComponents function itself. so we can provide meaningful error messages.

2023-11-17 14:39 UTC, abdullasulaiman commented on packages/vercel/src/components/connection/connection.module.scss
1. Make sure codeformatting done correctly
2. Please follow consistent naming convention
.loading-container
docsContainer
3. Please remove !important. If it is absolutely required otherwise not advisable
4. Don't use random values like 20px and 195px. Make sure if it is correct value use it every where as common token ( utility )

2023-11-17 14:39 UTC, abdullasulaiman commented on packages/vercel/src/components/docs-page/docs-page.module.scss
> +.container {
Make sure codeformatting done correctly
Please follow consistent naming convention
codeSample
Please remove !important. If it is absolutely required otherwise not advisable
Don't use random values like 20px and 195px. Make sure if it is correct value use it every where as common token ( utility )

2023-11-29 16:30 UTC, abdullasulaiman requested changes

2023-11-29 16:30 UTC, abdullasulaiman commented on packages/vercel/src/components/summary-page/summary-page.tsx
> +        console.log('err', error);
We should have some kind of info provided for use what's the actual error here ?

2023-11-29 16:30 UTC, abdullasulaiman commented on packages/vercel/src/components/summary-page/summary-page.tsx
> +            Embed Analytics in your app with this{' '}
just scan through all files for static strings and move to translation

2023-11-29 16:30 UTC, abdullasulaiman commented on packages/vercel/src/components/trusted-auth-page/trusted-auth-page.module.scss
> +  font-size: 20px;
standardize the font size and use it from common css

2023-11-29 16:30 UTC, abdullasulaiman commented on packages/vercel/src/components/trusted-auth-page/trusted-auth-page.module.scss
> +  font-size: 16px;
standardize the font size and use it from common css

2023-11-29 16:30 UTC, abdullasulaiman commented on packages/vercel/src/components/trusted-auth-page/trusted-auth-page.tsx
> +    getUserName(tsHostURL)
Can we create a common hooks to use it across the pages rather than duplicating on each component ?

2023-11-29 16:30 UTC, abdullasulaiman commented on packages/vercel/src/components/trusted-auth-page/trusted-auth-page.tsx
> +import React from 'preact';
make a common component and use it whereever applicable.
Ex
const { t } = useTranslations();
  const [userName, setUserName] = useState();
  const tsHostURL = formatClusterUrl(hostUrl.url);
  const [isLoading, setIsLoading] = useState(true);
  const codeMap = {
    SageEmbed: EmbedTemplates.TrustedAuthSageEmbed(
      tsHostURL,
      worksheetId,
      deploymentUrl,
      userName
    ),
  };
  even useEffect as well.

2023-11-29 16:30 UTC, abdullasulaiman commented on packages/vercel/src/components/trusted-auth-page/trusted-auth-page.tsx
> +      <Vertical style={{ padding: '16px' }}>
no hardcoding here. Can we use a common value =

2023-11-29 16:30 UTC, abdullasulaiman commented on packages/vercel/src/components/trusted-auth-page/trusted-auth-page.tsx
> +            IMPORTANT
move hardcoded string to Translation

2023-11-29 16:30 UTC, abdullasulaiman commented on packages/vercel/src/service/ts-api.ts
> +
const basePath = (hostUrl:string) => ${hostUrl}/api/rest/2.0
const v1basePath = (hostUrl:string) => ${hostUrl}/callosum/v1

2023-11-29 16:30 UTC, abdullasulaiman commented on packages/vercel/src/service/ts-api.ts
> +    headers: {
This we can move it to a utility function internally and use it across api

2023-11-29 16:30 UTC, abdullasulaiman commented on packages/vercel/src/service/ts-api.ts
> +    const response = await fetch(`${hostUrl}/callosum/v1/autogen/worksheet`, {
Break this entire block two different functions and handle thier error cases respectively

2023-11-29 16:30 UTC, abdullasulaiman commented on packages/vercel/src/service/vercel-api.ts
> +
Magic number which you are using for this PORT check can we do it better either checking the property of having a function which can be use in the destination file

2023-11-29 16:30 UTC, abdullasulaiman commented on packages/vercel/src/service/vercel-api.ts
> +    secuirtySettingsPromise(hostUrl, 'CORS', 'POST', updatedCORSPayload);
Why this line doesn't have await as this is post and handle the error seperately

2023-11-30 07:54 UTC, abdullasulaiman requested changes

2023-11-30 07:54 UTC, abdullasulaiman commented on packages/widgets/src/typography/typography.tsx
> +    <div dangerouslySetInnerHTML={{ __html: htmlContent }} {...props} />
Can we sanitize text before setting it to dangerouslySetInnerHTML. this is normally a secuirity risk.

2023-11-30 07:54 UTC, abdullasulaiman commented on packages/widgets/src/table-list-view/table-list-view.tsx
> +  const renderList = (listData) => {
Can we type this to listData: RowDataProps ?

2023-11-30 07:54 UTC, abdullasulaiman commented on packages/widgets/src/table-list-view/table-list-view.tsx
> +    return listData.map((item, index) => {
type : item: RowData, index: number

2023-11-30 07:54 UTC, abdullasulaiman commented on packages/widgets/src/table-list-view/table-list-view.module.scss
> +  margin-top: 6px;
why this is hardcoded to 6px ?

2023-11-30 07:54 UTC, abdullasulaiman commented on packages/widgets/src/table-list-view/table-list-view.module.scss
> +@import '../common.scss';
Make it to proper movement of css attributes like color, font-size etc

2023-11-30 07:54 UTC, abdullasulaiman commented on packages/widgets/src/header/header.tsx
> +  headerTitle?: string;
make headerTitle required based on the code logic

2023-11-30 07:54 UTC, abdullasulaiman commented on packages/widgets/src/header/header.module.scss
> +.header {
Scan through values and make sure they are used as common values

2023-11-30 13:25 UTC, adityamittal3107 commented on packages/widgets/src/table-list-view/table-list-view.tsx
> +    return listData.map((item, index) => {
DONE

2023-11-30 13:25 UTC, adityamittal3107 commented on packages/widgets/src/table-list-view/table-list-view.tsx
> +  const renderList = (listData) => {
DONE

2023-12-05 18:05 UTC, ashubham reviewed
Overall structure looks good to me.

2023-12-05 18:05 UTC, ashubham commented on packages/vercel/src/components/full-app/full-app.tsx
> +  const handleAllEmbedEvent = (event) => {
use the specific events, instead of `ALL`

2023-12-11 14:28 UTC, abdullasulaiman approved these changes
LGTM. Please merge and do the necessary review comments

2023-12-11 14:28 UTC, abdullasulaiman commented on packages/vercel/src/components/docs-page/docs-page.tsx
> +    if (worksheetId === '') {
Can we change this to await. Please make sure that worksheetId is empty where the datasource is not selected ?

2023-12-11 14:28 UTC, abdullasulaiman commented on packages/vercel/src/components/auth-type-none-page/auth-type-none-page.tsx
> +  const [newWorksheetId, setNewWorksheetId] = useState(worksheetId);
move fetchData and WhiteList method outside useEffect to make is more readable and I don't see any benefit having inside useEffect

2023-12-11 14:42 UTC, merged